name: Update games

on:
  schedule:
     - cron: "7 15 * * *" 
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v3

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "src/requirements.txt"

      - name: Run script
        run: |
          cd src
          python build_schedule_for_web.py
          
      - name: Push changes
        run: |
          pwd
          git config user.name Miguel Julián
          git config user.email figarocorso@gmail.com
          git add .
          git commit -m "Games automatically updated using GitHub Actions" || exit 0
          git push
