name: Update games

on:
  schedule:
     - cron: "7 15 * * *" 
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "src/requirements.txt"

      - name: Run script
        run: |
          cd src
          python build_schedule_for_web.py
          
      - name: Push changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: main
          rebase: 'true'
          commit-message: 'Games automatically updated using GitHub Actions'
